### ISSUE TITLE
Install-Cabal appears to fail

### ISSUE THREAD

**Issue by phsmenon** [kakkun61/ghcups#13]
Attempting to install cabal with something like `Install-Cabal 3.2.0.0` appears to fail.

This appears to be due to a call to an undefined function `Expand-Archive` in `ghcups.psm1` (line 502).

**Comment by phsmenon** [comment]
This appears to be because `Microsoft.PowerShell.Archive` somehow does not get imported on the machine. It is unrelated to `ghcups`. Sorry for the confusion.

**Comment by kakkun61** [comment]
Now I think that Microsoft.PowerShell.Archive will be installed automatically when installing ghcups, because I added Microsoft.PowerShell.Archive to required modules.
