### ISSUE TITLE
Cabal 3.4.0.0 not supported?

### ISSUE THREAD

**Issue by Mercurial** [kakkun61/ghcups#17]
Hi I just wanted to ask why the `cabal` version `3.4.0.0` is not supported?

Thanks!

**Comment by kakkun61** [comment]
Thank you for notifying me this!

The file name pattern of the binary archive of cabal-install seems to be changed after 3.4.0.0. And so I must change this PowerShell module.

Please wait for it!

**Comment by Mercurial** [comment]
I understand, glad to alert you with this issue then. 

Thanks!

**Comment by kakkun61** [comment]
I have released [version 4.3](https://www.powershellgallery.com/packages/ghcups/4.3) supporting cabal-install 3.4.0.0.

Please try it!

**Comment by Mercurial** [comment]
I will try it, thank you!
