### ISSUE TITLE
Install msys2?

### ISSUE THREAD

**Issue by TerrorJack** [kakkun61/ghcups#6]
For windows users, msys2 is needed when compiling packages like `network`. For this reason `stack` installs `msys2` along `ghc` by extracting a tarball. Maybe it's a useful thing to do here too; there's also `msys2` on chocolatey so that can be used if convenient.

**Comment by kakkun61** [comment]
I think GHC contains MSYS2 at _`$Env:ChocolateyInstall`\lib\ghc.8.8.1\tools\ghc-8.8.1\mingw_.

Do you mean that another MSYS2 is necessary?

I tried to build network with the following way, and it succeeded.

1. cabal init
2. add the dependency of network in the cabal file
3. cabal build .

**Comment by TerrorJack** [comment]
Ah, thanks for reminding that MSYS2 already exists for the chocolatey version.

**Comment by kakkun61** [comment]
No problems.

Not only the Chocolatey version, but also the distribution of <https://www.haskell.org/ghc/>.

![Path](https://user-images.githubusercontent.com/282593/70099865-68970800-1673-11ea-88b5-8eba64d26c06.png)
