### ISSUE TITLE
Show-Ghc only shows old ghc versions

### ISSUE THREAD

**Issue by spamviech** [kakkun61/ghcups#8]
Using Show-Ghc only displays old ghc-versions, even though a newer on (8.10.1) is already installed using chocolatey:
```
PS C:\WINDOWS\system32> Show-Ghc                                                                                        Chocolatey v0.10.15
ghc 8.0.1 [Approved] Downloads cached for licensed users
ghc 7.6.1.1 [Approved]
ghc 7.6.2.1 [Approved]
ghc 7.6.3.1 [Approved]
ghc 7.8.2.1 [Approved]
ghc 7.8.1.1 [Approved]
6 packages found.
```

Using `choco search` returns the current version
```
PS C:\WINDOWS\system32> choco search ghc                                                                                Chocolatey v0.10.15
ghc 8.10.1 [Approved]
haskell-dev 0.0.1 [Approved]
cabal 3.2.0.0 [Approved] Downloads cached for licensed users
haskell-stack 2.3.1 [Approved] Downloads cached for licensed users
idris 1.1.1 [Approved] Downloads cached for licensed users - Possibly broken for FOSS users (due to original download location changes by vendor)
5 packages found.
```

Running in an admin-PS session with german region and Beta-UTF8-support enabled.
Current Codepage is 65001 (UTF-8).

**Comment by kakkun61** [comment]
The following is the part of this issue.

https://github.com/kakkun61/ghcups/blob/542b81c3d6eb563e71bbf14346dae4093095262a/ghcups.psm1#L327

This is maybe a Chocolatey issue. It seems that the `--all-versions` option removes the newest version.

```
PS C:\> choco list ghc --by-id-only
Chocolatey v0.10.15
ghc 8.10.1 [Approved]
1 packages found.
PS C:\> choco list ghc --by-id-only --all-versions
Chocolatey v0.10.15
ghc 8.4.3 [Approved]
ghc 8.0.2 [Approved] Downloads cached for licensed users
ghc 8.8.1 [Approved]
ghc 8.6.1.1 [Approved]
ghc 8.6.1 [Approved]
ghc 8.0.2.1 [Approved]
6 packages found.
```

# TODO

- check again
- search Chocolatey issues
- report the issue to Chocolatey

**Comment by kakkun61** [comment]
This issue https://github.com/chocolatey/choco/issues/1982 saids

> This may be due to caching with chocolatey.org and issues over there.

**Comment by kakkun61** [comment]
First, the Chocolatey repository has more many versions of the GHC.
https://chocolatey.org/packages/ghc#versionhistory

**Comment by kakkun61** [comment]
After version 3.0, ghcups doesn't depend on the Chocolatey.

Now `Show-Ghc` returns:

```
> Show-Ghc -HumanReadable
8.10.1   S H:\ghcups\ghc-8.10.1
8.8.3    S
8.8.2    S
8.8.1    S
8.6.5    S
8.6.4    S
8.6.3    S
8.6.2    S
8.6.1    S
8.4.4    S
8.4.3    S
8.4.2    S
8.4.1    S
8.2.2    S
8.2.1    S
8.0.2    S
8.0.1    S
S: supported
```

@spamviech, if you don't mind, close this issue.

**Comment by spamviech** [comment]
Yes, works great now.
Don't want to look at the code, but couldn't help to notice a `version.yaml`.
Does this mean ghcups has to be updated with ever new ghc/cabal version?
If so, what is the corresponding command?

PS:
You should add to your ReadMe, that 7-zip has to be in the PATH-Variable.

**Comment by kakkun61** [comment]
Thank you for checking.

> Does this mean ghcups has to be updated with ever new ghc/cabal version?

No, when new versions will have the same URL patterns to distribute and the same installation processes. When they will be changed, fixes of ghcups get to be necessary.

The versions in _version.yaml_ have the same ones.

> If so, what is the corresponding command?

`Update-Module` is.

> You should add to your ReadMe, that 7-zip has to be in the PATH-Variable.

Yes, you are right!
